# Copyright 2019 Kuei-chun Chen. All rights reserved.
version: "3"

services:
  grafana-ftdc:
    image: simagix/grafana-ftdc
    hostname: grafana-ftdc
    ports:
      - "3030:3000"
    environment:
      GF_INSTALL_PLUGINS: grafana-simple-json-datasource

  ftdc:
    image: simagix/ftdc:1.0
    hostname: ftdc
    volumes:
      - ./diagnostic.data:/diagnostic.data
    command: /simple_json /diagnostic.data
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 512M
