[[constraint]]
  version = "v1.1.1"
  #branch = "master"
  name = "go.mongodb.org/mongo-driver"

[[constraint]]
  branch = "master"
  name = "github.com/simagix/gox"

[prune]
  go-tests = true
  unused-packages = true
